### ISSUE TITLE
typealiasing action, state, and observation

### ISSUE THREAD

**Issue by haoyio** [sisl/POMDPs.jl#17]
For clarity when defining functions, why not `typealias` `Action`, `State`, and `Observation` to `Any`?

**Comment by etotheipluspi** [comment]
In your example, can the user do this:
```julia
type MyState <: POMDPs.State
    ...
end
```
To make the state compatible with POMDPs.jl? 

I agree that having abstract types for states, actions and observations can add extra overhead to the user, but hopefully that overhead is minimal.

I'm going to go ahead and add these unless there are objections.

**Comment by ebalaban** [comment]
Hm... I like the idea of having abstract POMDPs.jl action, observation, 
and action types (and rewards, I was going to bring that up in a 
different context), but don't really like having wrappers when those 
objects are just concrete integers, floats, etc. Can we, perhaps, 
briefly talk about this after the meeting today?

**Comment by mykelk** [comment]
Yeah, we can discuss.

**Comment by zsunberg** [comment]
Max, the user may *not* be able to do what you suggest because they may have their own type heirarchy already in place. This is especially a problem if they are using some other package that requires them to subtype an abstract type.

For example what if they are also using a hypothetical motion planning package, `MotionPlanning.jl`? Then `MyState` might also be a subtype of 'MotionPlanning.State`. The person would have to use composition to be compatible with one of the packages.

**Comment by etotheipluspi** [comment]
Updated and closed the issue. Make sure to update your state action and observation definitions.
