### ISSUE TITLE
Abstract simulate

### ISSUE THREAD

**Issue by mykelk** [sisl/POMDPs.jl#22]
An idea is to keep simulate abstract (meaning have it just error out in POMDPs.jl) and provide some basic implementations in POMDPToolbox.jl. As mentioned in #19, the idea comes from RLGlue. See fig. 2 of this [paper](http://www.jmlr.org/papers/volume10/tanner09a/tanner09a.pdf). You will see the "agent program" (policy), the "experiment program" (simulator), and the "environment program" (pomdp).

We seem to have two options:
1. Commit to keeping POMDPs.jl implementation free. Provide a basic implementation in POMDPToolkit.jl.
2. Provide a basic implementation of simulate in POMDPs.jl for educational reasons (as suggested by @zsunberg). Of course, we can just include a basic implementation in the documentation of POMDPs.jl and not necessarily in the code itself (with the idea of keeping POMDPs.jl pristine).

**Comment by zsunberg** [comment]
From my experience implementing things so far, it is kind of awkward to have optional arguments in the interface functions. Also, while I agree that `initial_belief` is the most important of the optional arguments that we might consider including, there are others that are also important, for example `initial_state` will often need to be specified, not to mention the random number generator. Rather than trying to decide which of these should go in the simulate interface function, I think the best solution is to roll them all up into the simulator object, put some good examples in POMDPToolbox, and let simulator-implementors decide what is needed.

**Comment by etotheipluspi** [comment]
I like Zach's idea. I think having good examples and simplified function definitions is the way to go.

**Comment by zsunberg** [comment]
I think we've reached consensus on this.
