### ISSUE TITLE
POMDP belief representations vs solver/belief updater belief representations

### ISSUE THREAD

**Issue by ebalaban** [sisl/POMDPs.jl#33]
Here is an issue with our current approach to belief management:

- initial_belief() or create_belief() return a belief representation that's problem-specific (i.e. POMDP-specific). For the purposes of explanation, let's assume that initial_belief(my_pomdp) returns a 10-element vector of particles that is then stored in current_belief.

- Now, in my [online] solver, I'd like to use a higher-fidelity 500-particle belief representation. Furthermore, I'd also like to use the same 500-particle representation for maintaining the belief state in the simulation loop (via our belief() function).

- It would, obviously, be undesirable to try to convert back and forth between the 10-particle (POMDP) and 500-particle (solver/belief updater) representations.

Here are a few possible solutions:

1. During the first iteration of the simulation, the belief structure is converted from 10 to 500 particles inside action(), then, again, inside belief() (current_belief goes into belief() as a 10-particle vector, then comes out as a 500-particle updated_belief). Both current_belief and updated_belief then remain 500-particle vectors until the end of the simulation. Kind of ugly, especially since we'd have to ensure that conversions inside action() and belief() are done in an exactly the same way (alternatively, we need to return the converted belief vector from action() and pass it into belief()).

2. Use a wrapper type, like what Zach uses, and change the actual representation within that wrapper structure. This, to me, is not all that different from the first option and also requires the user to know about some MyBeliefWrapper type and construct an instance of it before calling action() and belief().

3. Add initial_belief() and create_belief() versions that take the solver and the belief updater as arguments and return a belief structure that's tailored to solver/belief updater needs from the very beginning. We would still retain the current versions of  initial_belief() and create_belief(), of course:

create_belief(pomdp::POMDP)
create_belief(pomdp::POMDP, solver::Solver, bu::BeliefUpdater)

initial_belief(pomdp::POMDP, belief = create_belief(pomdp))
initial_belief(pomdp::POMDP, solver::Solver, bu::BeliefUpdater, belief = create_belief(pomdp))

The third option is my preferred solution (assuming that we go ahead and implement the BeliefUpdater type, see #32), but I am open to other ideas, of course.

**Comment by zsunberg** [comment]
I think this is probably a good idea. I think that we need to create a new function for it though. For example, it could be

```julia
specialize_belief(pomdp::POMDP, belief::Belief, solver::Solver) = belief
```

(the `= belief` would just be the default implementation for the case when the solver doesn't need a modified belief). We can of course add the `BeliefUpdater` if we decide to add that to the interface.

The reason that this is necessary is that a user may need to specify an initial belief for a simulation that is different from the belief returned by `initial_belief(pomdp)`, and if we overloaded `create_belief` and `initial_belief` as above, there would be no way to convert a belief that the user specified for use with the solver. `specialize_belief` could be called within `simulate` to automatically convert the belief for an arbitrary solver.

**Comment by zsunberg** [comment]
Actually, I think belief should be specialized based on the policy, not the solver. i.e.

```julia
specialize_belief(pomdp::POMDP, belief::Belief, policy::Policy) = belief
```

**Comment by mykelk** [comment]
I'm starting to get a bit lost now. I think we are now discussing something that is specific to certain solvers, not about the general API. Right?

**Comment by zsunberg** [comment]
It is specific to a potentially large class of solvers, so I think it may be worth including in the API.

The basic problem is this: POMCP (and DESPOT from what I understand) are not just solvers, they also maintain an approximate belief representation*. In my opinion, the best way to implement this is to give the solver control over the belief. I think this is the most flexible way of standardizing it.

* POMCP, for example, re-uses the tree simulations to update a particle filter
** it would be impossible to implement this only within solver code such as `action()` because the solver does not have access to the observations from the real world.

**Comment by zsunberg** [comment]
It would be great to be able to use POMCP and DESPOT as described in the literature interchangeably with something like value iteration, e.g.:

```julia
solvers = {DiscreteValueIteration(...), POMCP(...)}

problem = BabyPOMDP(...)

rewards = Array(Float64, length(solvers))
for i in 1:length(solvers)
    simulator = RolloutSimulator(rng=MersenneTwister(i), eps=0.001) # same rng to keep things fair
    rewards[i] = simulate(simulator, problem, solvers[i])
end
```

If we want to do this, we need a function like `specialize_belief()`.

Side note: currently POMCP has a fallback mode, so it will work if used like this, but it will not use the particle filter and will not be able to reuse tree data from previous steps; it will use exact belief updates and will create a completely new tree at every step

**Comment by mykelk** [comment]
Hmmm... Okay. Is `specialize_belief` the right name? It feels a little strange.

**Comment by ebalaban** [comment]
@zsunberg, I am thinking about this in, possibly, even more general terms. In the POMDP definition belief is represented as a distribution of type DistType1. In the solver being used to solve the POMDP (and possibly the belief updater) the implemented way of representing belief is DistType2. Going between DistType1 and DistType2 is ugly and/or lossy. So, my preference would be to use DistType2 from the start. I think this issue might crop up for most solvers, not just POMCP, DESPOT, and the like.

**Comment by ebalaban** [comment]
I am not opposed to introducing another function to the API (e.g. specialize_belief), but I still might not be fully understanding the need for one (as opposed to having a couple versions of create_belief() and initial_belief()). I think may be I need to read Zach's first comment again :-)

**Comment by zsunberg** [comment]
@ebalaban, in response to your first comment, if we want our solvers to work with arbitrary problems, we will have no choice but to do the lossy conversion. If I was to write `initial_beilief(problem::POMDP, solver::POMCPSolver)`, I would use `initial_belief(problem)` inside my function so that I can get the initial distribution for any pomdp that someone might throw at me, then I would have to sample this belief to create particles for my filter.

**Comment by zsunberg** [comment]
MCVI is another example of a solver that would need this I think

**Comment by zsunberg** [comment]
Another potential use for this is when a user hand-specifies a simple policy that does not feed back on the belief that is default for the pomdp. For example, a policy for the crying baby problem that feeds the baby whenever it is crying depends only on the previous observation. It cannot use `BabyStateDistribution` as the belief that it feeds back on, but instead must get the previous observation through  the belief (I have implemented this as `PreviousObservation` in `POMDPToolbox`

**Comment by zsunberg** [comment]
@mykelk I haven't been able to think of a name better than `specialize_belief`. Perhaps it feels strange because this is not typically discussed in the literature or by researchers - people don't typically try to make offline solvers and online approximate solvers live in the same ecosystem as we are attempting. There definitely could be a better name though.

**Comment by ebalaban** [comment]
@zsunberg, after re-reading this thread this morning with a less tired brain, I think I understand what you hope to accomplish with specialize_belief() - anytime conversion from one belief representation to another. Am I right? What I had in mind is something slightly different (and, perhaps, less ambitious).

A problem writer may not give too much thought to belief state representation if he/she does not know which solvers will be used to solve the problem. On the other hand, if another user wants to be able to easily work with a particular solver, he/she can add a function that supplies belief state in the appropriate representation. Using a rover as my running example (no pun intended), what I envision happening is something like this:

# I am too lazy to think about this, so let me just say that the rover state is
# distributed normally in the default case and let others worry about everything else
initial_belief(pomdp::POMDP)
    return GaussianBelief(50, 5)
end

# Ok, well, I do want my problem to work well with DESPOT though, so I'll add a function that supplies DESPOT with its
# preferred particle representation instead
initial_belief(pomdp::POMDP, solver::DESPOTSolver)
    # create a bunch of particles here that describe where we think we are
    return [Particle{Int64}(50, 0.5), Particle{Int64}(49, 0.2), Particle{Int64}(51, 0.2), Particle{Int64}(48, 0.05), Particle{Int64}(52, 0.05)]
end

# Now, my adviser wants me to try some other solver that expects all states enumerated and probabilities
# for them specified, even if the state is physically on the other side of the solar system from where
# my rover is
initial_belief(pomdp::POMDP, solver::SomeOtherSolver)
    return create_a_humongous_table_of_states_and_their_darn_probabilities(...)
end

So, if you need to tweak your belief state later on, before using it within your simulation, you'd just tweak it in one of the above representations, e.g. change the mean of the Gaussian representation to 49 and its standard deviation to 4. Note that the representation returned for DESPOT never existed as a Gaussian (and vice versa), so there is no "loss" to speak of - both representations just have their pluses and minuses. And yes, you'd still be able to try a bunch of different solvers with BabyPOMDP, you'd just need to call initial_belief() for each of the solvers to return the appropriate belief representation.

None of this precludes writing "lossy" converters from one type of belief representation to another, we just may want to keep them in POMDPToolbox and not in the API.

Does this make sense? I'll respond to the BeliefUpdater discussion a bit later.

**Comment by mykelk** [comment]
Thank you for your example. I think these converters can live in POMDPToolbox or something like that.

**Comment by zsunberg** [comment]
Sorry you had trouble deciphering what I was saying - actually, I was not attempting to define an interface for "anytime" conversion between belief types with `specialize_belief()`, rather, I was trying to define a standard way to create a policy-specific belief structure with any arbitrary belief as the initial belief.

Before discussing this more, I think we should answer this question: Is the output of `initial_belief()` the only way of specifying the initial belief that we want to support? I.e. if we have a for loop that runs 50 simulations with 50 different initial beliefs, do we want to redefine `initial_belief()` (or alternatively change pomdp parameters to get `initial_belief()` to return something different) 50 times?

**Comment by ebalaban** [comment]
Yes, I'd say we either modify POMDP parameters and call initial_belief() again or tweak a previously-generated belief directly. What other options do you have in mind?

**Comment by zsunberg** [comment]
Ok, now I think I am seeing what you were proposing. You are trying to give a user (we'll call him the experimenter - it may or may not be the problem writer or the solver writer) more fine grain control of the belief. I was trying to propose a way to facilitate transparent policy interchangeability for simple problems (that is solving the problem that the experimenter would need to know about a policy-specific belief). I'll not discuss that in this issue any more.

I think the easiest and most flexible way to specify the initial belief for a simulation is to directly specify it to the simulator. For example, as the RolloutSimulator in POMDPToolbox is implemented now (don't get distracted by the word 'Rollout' - I'm not talking about rollout simulations, that is just the name of a simulator that has already been implemented), you could do

```julia
sim = RolloutSimulator(initial_belief=[Particle{Int64}(50, 0.5), Particle{Int64}(49, 0.2), Particle{Int64}(51, 0.2), Particle{Int64}(48, 0.05), Particle{Int64}(52, 0.05)])
simulate(sim, pomdp, policy)
```
where `policy` is a DESPOT policy.

I was under the impression that `initial_belief()` was just a convenience function so that an experimenter can generate an example initial belief for a problem without having to think about it too much. I personally think giving the initial belief to the simulator should be the preferred way to specify the initial belief, rather than redefining the `initial_belief()` function, especially since there may be calls to `simulate()` for rollouts deep inside an online policy and it would be awkward to redefine initial belief there. I suppose there is not really any big harm in adding the policy to the `initial_belief()` arguments, but I don't think it is necessarily needed either.

It is true that the more different/optional ways we provide for doing things, the more likely it is that a solver-writer or simulator-writer or problem-writer will decide not to support it at some point and the more times solvers/simulators/problems will be incompatible, the more frustrating using this thing will be.

I do see the point that you would need `create_belief()` to be aware of the policy (I think it should be the policy, not the solver, since policy is the argument to `simulate()`), so I do agree that should be changed.

**Comment by zsunberg** [comment]
What will happen though if
```
create_belief(::BabyPOMDP, ::Policy)
```
is defined in POMDPModels.jl and
```
create_belief(::POMDP, ::POMCPPolicy)
```
is defined in POMCP.jl. can julia distinguish those?

**Comment by zsunberg** [comment]
This should be fixed by #34, so we'll put this on hold until we get that all figured out

**Comment by zsunberg** [comment]
@ebalaban should we close this and move further discussion to #35?

**Comment by ebalaban** [comment]
Sure.
