### ISSUE TITLE
reward should only have the reward(state, action, statep) method

### ISSUE THREAD

**Issue by zsunberg** [sisl/POMDPs.jl#40]
Currently, if a solver uses `reward(s, a)`, it will not work with any problems that have reward defined based on s, a, s'. We either need to only have one method available (this is my preference, and what we decided to do for `observation`), or document that solvers must use the s, a, s' version.

**Comment by ebalaban** [comment]
I was thinking about the same thing yesterday, actually. I'd say we should go with a single reward(s,a,s') function (to be consistent with observations).

**Comment by etotheipluspi** [comment]
Is there any other reason for having the ```reward(s,a,s')``` form other than its resemblance to the observation function? 

I find the ```reward(s,a)``` form much easier to deal with especially in iterative solvers, i.e. value iteration. It also makes the reward function easier to define, because you only need to worry about the immediate state and not where you may wind up. My vote is to keep the reward function the way it is.

**Comment by zsunberg** [comment]
Here are the consequences of each possible choice (basically the same consequences as for `observation`):

### `reward(s,a)` only
No way (other than state augmentation) to express problems for which the reward is correlated with the state transition, e.g. when a robot travels a stochastic distance in response to an action and the reward is based on that distance.

### `reward(s,a,s')` only
Kind of a pain to use with some solvers (e.g. value iteration). It would be up to the solver writer to check/warn the user/make it clear in the documentation that s' is a dummy argument or something.

### keep both (the way it currently is)
If a solver writer unwittingly uses `reward(s,a)` in their solver, it won't work with problems that define `reward(s,a,s')` (this problem may be mitigated with proper documentation)

Other notes:
- @etotheipluspi says `reward(s,a)` "makes the reward function easier to define". I don't think it is actually true that it makes things any easier for the problem writer. It is trivial to simply ignore the third argument in your function definition, i.e. use the signature `reward(s::MyState, a::MyAction, ::State)` (note the unnamed third argument).
- If we keep both, we should use the default implementation `reward(s::State, a::Action, ::State) = reward(s, a)` so that problem writers only have to implement `reward(s,a)` and sampling-based solvers can always use `reward(s,a,s')` to handle all problems.

I think having `reward(s,a,s')` only requires the least explanation (i.e. we did this because it's most general), so that is my vote, but I don't feel super strongly about it.

**Comment by ebalaban** [comment]
I agree with @zsunberg on this (and would have probably used the same example to make the argument...). It may help to think of costs (e.g. energy) instead of rewards for cases like robots/rovers for reward(s,a,s') to make a more intuitive sense. I am fine with either option 2 or option 3 that @zsunberg listed. Whichever one we select though, we should go with the same for observations, to be consistent.

**Comment by zsunberg** [comment]
Yeah, I'm ok with option 3 as well, but I think we should document that solvers should use the (s,a,s') versions as often as possible for compatibility's sake.

**Comment by etotheipluspi** [comment]
@zsunberg  you're right. The implementation of ```reward(s,a,s')``` would actually be trivial for problems where reward doesn't depend on s'. I rest my case, and vote for option 2.

**Comment by zsunberg** [comment]
Ok, if there aren't any objections, I'm going to get rid of `reward(s, a)` on Monday

**Comment by ebalaban** [comment]
Sounds good to me.
