### ISSUE TITLE
Require ==, hash(), and iterator functions for State, Action, and Observation types?

### ISSUE THREAD

**Issue by ebalaban** [sisl/POMDPs.jl#46]
For DESPOT I need to use states, actions, and observations as associative keys in various places. I also find it useful to be able to determine, for example, if two different Action objects represent the same exact action. So far the cleanest solution I found is defining the == operator (and thus isequal()) and the hash() function for each of the types in the problem code, so that they can be used in dictionaries and such.

Likewise, at least for the time being, I need to iterate through ranges of states, actions, and observations, so I've implemented start(), next(), and done() for each of the types.

I am guessing that this will be useful to more solvers than just DESPOT. If so, should we require that problem writers provide these operators/functions along with the state, action, and observation types? Can you think of a more elegant solution? We already have index() for discrete POMDP states in the interface, by the way. It would be replaced by hash(), which would just return the state index in the simplest case or some unique user-defined hash number for a more complex representation. Same for actions and observations.

**Comment by zsunberg** [comment]
Yeah, I have been using hash and == as well. I think this is the best
solution in cases where there may be sparse sampling such as MCTS, DESPOT,
and POMCP. I think in other cases there may be a benefit to storing things
in an Array rather than a Set or Dict, so index()  is appropriate. Thus, I
think both index and hash,== should exist side by side for their different
purposes.

Currently `domain()` is supposed to return an iterable representation of an
AbstractSpace, implying that the returned object should have start(),
next() and done().

Can you elaborate a little bit more on the iteration through ranges? Is
iterating through ranges something that other solvers might need, or do you
think it is DESPOT specific?

**Comment by ebalaban** [comment]
Sorry, I somehow missed domain() in the docs. I'll comment more on it in #47. I am fine with retaining index(), as long as we make clear that it's meant for sequential numbering, as opposed to hash(), which does not guarantee any particular ordering, only uniqueness. As for ranges/subsets, for now that's specific to the DESPOT extensions I am working on. I am still playing around with how to handle that. Once I have a better idea, I might propose something for the interface. For the purposes of this discussion, let's assume that we are iterating through the entire state/action/observation space.

**Comment by etotheipluspi** [comment]
I agree with the idea of adding == and hash to the master table, i.e. the table of all the functions the users must define to use all the solvers. However, if the user is not using Tree Search solvers (MCTS, POMCP, DESPOT), they shouldn't be required to write those functions. I'm guessing that's implied in the issue, but I just wanted to clarify.

**Comment by mykelk** [comment]
I agree with @etotheipluspi.

**Comment by ebalaban** [comment]
Yes, that's fine.

**Comment by ebalaban** [comment]
Ok, the iterator issue is handled in #47 and solvers that need *==* and *hash()* will have to stipulate that in their documentation. Since there are really no other actions that need to be taken on this issue, I'll go ahead and close it. Please reopen if you think that something else needs to be done here.
