### ISSUE TITLE
Naming of solver

### ISSUE THREAD

**Issue by mykelk** [sisl/POMDPs.jl#51]
Should the convention be for packages to define things like `SARSOPSolver`, or should it be just `Solver` for simplicity? And when necessary use `SARSOP.Solver`?

**Comment by ebalaban** [comment]
I have a slight preference for going with SARSOP.Solver instead of SARSOPSolver, for both simplicity and uniformity. If we do decide to go this way, the same should, of course, apply to other types (e.g. I define DESPOTPolicy, DESPOTParticle, DESPOTBelief, etc).

**Comment by etotheipluspi** [comment]
I would avoid generic names like ```Solver```, because that can lead to conflicts when multiple solvers are used in the same program, e.g. comparing policies. 

Although I'm not sure it's a big issue, when you look at the type of something like ```SARSOP.Solver``` in v0.4, it will actually show up as ```SARSOP.SARSOP.Solver```, since the type carries the module name in front of it as well which can be awkward/confusing. My preference is for the ```SARSOPSolver``` convention.

**Comment by tawheeler** [comment]
I think @mykelk is suggesting that we don't export `Solver` so that we have to refer to them as Module.Solver, so there shouldn't be conflicts.
POMDPS.jl currently exports `Solver`, so we may have to change that to AbstractSolver.

The pros of going with `SARSOP.Solver` are:
- shorter naming for code written in the solver module (We could typealias to something short to get a similar effect)

The pros of going with `SARSOPSolver' are:
- most solvers will be referred to on the abstract for code not written in their module, which would use use `::AbstractSolver`

Autocompletion should work either way, I think.

My gut instinct is to use `SARSOPSolver`, but either way is fine.

**Comment by etotheipluspi** [comment]
@tawheeler I see. 

I don't see anything regarding this in the style guide. If there is previous convention we should adopt it. Although not exporting a type that we want the user to use seems pretty odd to me. 

My vote is still to stick with ```SARSOPSolver```.

**Comment by mykelk** [comment]
Sounds good. We can stick with `SARSOPSolver`.

**Comment by zsunberg** [comment]
I think SARSOPSolver is better because future packages might contain
multiple solvers.
